name: Moneymine
main: com.icloud.jxthibeault.moneymine.Moneymine
version: alpha2.0.3.3
commands:
  createjob:
    usage: /createjob jobname wage
    permission: moneymine.createjob
  setuniform:
    usage: /setuniform job helmetMaterial chestplateMaterial leggingsMaterial bootsMaterial
    permission: moneymine.setuniform