name: Moneymine
main: com.icloud.jxthibeault.moneymine.Moneymine
version: alpha-2.0.2

commands:
  createjob:
    description: Command for creating a new job.
    usage: /createjob [jobname] [wage]
    permission: moneymine.job.create
    permission-message: You don't have access to that command.
  setuniform:
    description: Command for setting the uniform for a job.
    usage: /setuniform [job] [helmet  material] [chestplate material] [leggings material] [boots material]
    permission: moneymine.uniform.set
    permission-message: You don't have access to that command.