name: Moneymine
main: com.icloud.jxthibeault.moneymine.Moneymine
version: alpha2.0.3
commands:
  createjob:
    description: Command for creating a new job.
    usage: /createjob jobname wage
    permission: moneymine.createjob
  setuniform:
    description: Command for setting the uniform for a job.
    usage: /setuniform job helmetMaterial chestplateMaterial leggingsMaterial bootsMaterial
    permission: moneymine.setuniform