name: Moneymine
main: com.icloud.jxthibeault.moneymine.Moneymine
version: alpha-1.0.6
commands:
  openapp:
    description: Open job to applicants.
    usage: /createapp [jobname] [payment] [jobrequirements]
    permission: moneymine.openapp
  closeapp:
    description: Close a job to applications.
    usage: /closeapp [job]
    permission: moneymine.closeapp